name: insurance_mobile_app
description: "Insurance Mobile App MVP — case study implementation."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.1
  dio: ^5.9.2
  go_router: ^17.2.2
  intl: ^0.20.2
  equatable: ^2.0.8
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/mock/
    - assets/languages/
